export const ALL_PRODUCT_LOADING = "ALL_PRODUCT_LOADING";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_LOADING = "PRODUCT_DETAILS_LOADING";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";


export const CLEAR_ERROR= "CLAER_ERROR";